# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 64 # def: 64

# Directories
train_folder: /home/data/ilsvrc12-hkl-64/train_hkl_b64_b_64/
val_folder: /home/data/ilsvrc12-hkl-64/val_hkl_b64_b_64/
