# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 128 # def: 256

# Directories
train_folder: /home/yma/imagenet/data128/train_hkl_b128_b_128/
val_folder: /home/yma/imagenet/data128/val_hkl_b128_b_128/