# If want to input None, use !!null

gpu0: 'gpu0'
gpu1: 'gpu1'
sock_gpu: 5000
sock_data0: 5001
sock_data1: 5002

batch_size: 128 # def: 128

# Directories
train_folder: /home/yma/imagenet/data/train_hkl_b256_b_128/
val_folder: /home/yma/imagenet/data/val_hkl_b256_b_128/
