# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 30 # def: 256

# Directories
train_folder: /home/yma/imagenet/data/train_hkl_b256_b_256/
val_folder: /home/yma/imagenet/data/val_hkl_b256_b_256/