# If want to input None, use !!null

gpu: 'gpu0'
sock_data: 5001

batch_size: 64 # def: 64

# Directories
train_folder: /home/yma/imagenet/data/train_hkl_b64_b_64/
val_folder: /home/yma/imagenet/data/val_hkl_b64_b_64/