# If want to input None, use !!null

gpu0: 'gpu0'
gpu1: 'gpu1'
sock_gpu: 5000
sock_data0: 5001
sock_data1: 5002

batch_size: 32 # def: 32

# Directories
train_folder: /home/data/ilsvrc12-hkl-64/train_hkl_b64_b_32/
val_folder: /home/data/ilsvrc12-hkl-64/val_hkl_b64_b_32/
